name: buildWindow

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-window:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install CMake and Make
        run: |
          choco install cmake make

      - name: Display CMake and Make versions
        run: |
          cmake --version
          make --version

      - name: Execute Makefile
        run: make